use_frameworks!

target 'SwiftFlyer_Example' do
  pod 'SwiftFlyer', :path => '../'

  target 'SwiftFlyer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.1'
  end
end
